apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - name: todo-backend
      port: 8000
      targetPort: 8000
      protocol: TCP