apiVersion: v1
kind: Pod
metadata:
  name: app-log-sidecar
spec:
  volumes:
  - name: logs
    emptyDir: {}

  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "$(date) App log entry" >> /var/log/app/app.log;
          sleep 5;
        done
    volumeMounts:
    - name: logs
      mountPath: /var/log/app

  - name: log-reader
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - tail -F /var/log/app/app.log
    volumeMounts:
    - name: logs
      mountPath: /var/log/app
