apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-pod
  labels:
    db: mysql
spec:
  containers:
    - name: mysql-container
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root123
