apiVersion: v1
kind: Pod
metadata:
  name: jenkins-env-pod
  labels:
    automate: jenkins
spec:
  containers:
    - name: jenkins-container
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080
      env:
        - name: ENVIRONMENT
          value: "development"
        - name: APP_NAME
          value: "jenkins-web"
        - name: APP_VERSION
          value: "1.0"
