apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: ENVIRONMENT
          value: "production"
        - name: APP_NAME
          value: "nginx-web"
        - name: APP_VERSION
          value: "1.0"
